name: Reusable Workflow User

on: [push]

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/dockerCompose.yml
    with:
      compose-file: "docker-compose.yml" # Optional input if needed

  call-automation-testing:
    uses: ./.github/workflows/automationTestingWithPlaywright.yml
    with:
      python-version: "3.10" # Optional input if needed
